---
- name:  Deploy and start Apache HTTPD service
  hosts: webserver
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python-httplib2
    rule: http

  tasks:
    - name: Require packages are installed and up to date
      yum:
        name: 
          - "{{ web_pkg }}"
          - " {{ firewall_pkg }}"
          - "{{ python_pkg }}"
        state: latest
    - name: The {{ firewall_service }} service is started and enabled
      service:
        name: "{{ firewall_service }}"
        enabled: yes
        state: started
    - name: THe {{ web_service }} service is started and enabled
      service:
        name: "{{ web_service }}"
        enabled: yes
        state: started
    - name: Web content is in place
      copy:
        content: "Example web content"
        dest: /var/www/html/index.html
    - name: the firewall port for {{ rule }} is open
      firewalld:
        service: "{{ rule }}"
        permanent: yes
        immediate: yes
        state: enabled

- name: Verify the Apache service
  hosts: localhost
  become: no
  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: http://servera.lab.example.com
        status_code: 200