---
# tasks file for stundent.myenv
- name: if myenv_user is empty just fail
  fail:
    msg: You must specify the variable 'myenv_user' to use this role
  when: "myenv_user ==''"

- name: Install package {{ myenv_packages }} package
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ myenv_packages }}"

- name: copy stande profile picture
  copy:
    src: system-logo-icon.png
    dest: /home/{{ myenv_user }}/profile.png

- name: Make sure line "alias tree = 'tree -C'" is in .bashrc
  lineinfile:
    path: /home/{{ myenv_user }}/.bashrc
    line: alias tree = 'tree -C'
    state: present

- name: template place mkcd.sh.j2 in /etc/profile.d/mkcd.sh
  template:
    src: mkcd.sh.j2
    dest: /etc/profile.d/mkcd.sh
    owner: root
    group: root
    mode: 0644
