
  - name: check to see if httpd is installed
    shell: rpm -q httpd
    register: rpm_check
    failed_when: rpm_check.rc == 1
  - block:
    - name: get_uri {{ https_uri }} to /etc/httpd/conf.d/
      get_url:
        url: "{{ https_uri }}"
        dest: /etc/httpd/conf.d/
    - name: file create ssl directory under /etc/httpd/conf.d/
      file:
        path: /etc/httpd/conf.d/ssl
        state: directory
        recurse: yes
        mode: 0755
    - name: file cretae logs directory under /var/www/html
      file:
        path: /var/www/html/log
        state: directory
        recurse: yes
        mode: 0755
    - name: stat check to make sure /etc/httpd/conf.d/ssl.conf exists
      stat:
        path: /etc/httpd/conf.d/ssl.conf
      register: ssl_conf_file
    
    - name: rename ssl.conf to ssl.conf.bak
      shell: mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.bak
      when: ssl_conf_file.stat.exists
    
    - name: get ssl cert file and extract it to /etc/httpd/conf.d/ssl
      unarchive:
        src: "{{ ssl_uri }}"
        dest: /etc/httpd/conf.d/ssl/
        copy: no
      notify: restart_services
    
    - name: create index.html file under /var/www/html
      copy:
        content: "{{ ansible_fqdn }} ({{ ansible_default_ipv4.address }}) has been customized by Ansible\n"
        dest: /var/www/html/index.html
    when: 
      rpm_check.rc == 0