---
- name: Enable internet services
  hosts: serverb.lab.example.com
  become: yes
  tasks:
  - name: latest version of httpd and firewalld installed
    yum:
      name: 
        - httpd
        - firewalld
        - php
        - php-mysql
        - mariadb-server
      state: latest
  - name:  firewalld enabled and running
    service:
      name: firewalld
      enabled: yes
      state: started
  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes
  - name: httpd enabled and running
    service:
      name: httpd
      enabled: yes
      state: started
  - name: mariadb enabled and running
    service:
      name: mariadb
      enabled: yes
      state: started
  - name: GET_URL 
    get_url:
      url: "http://materials.example.com/grading/var/www/html/index.php"
      dest: /var/www/html/index.php
      mode: 0644


- name: Test intranet web server
  hosts: localhost
  become: no
  tasks:
  - name: connect to intranet web server
    uri:
      url: http://serverb.lab.example.com
      status_code: 200
  