---
- name: Install and configure lamp
  hosts: lamp
  vars: 
    firewall: firewalld
  tasks:
    - name: Inclodu the variable file
      include_vars: vars/main.yml
    - name: include tasks
      include: tasks/main.yml
    - name: Install the firewall
      yum:
        name: "{{ firewall }}"
        state: latest
    - name: Start the firewall
      service:
        name: "{{ firewall }}"
        state: started
        enabled: yes
    - name: Open the port for the web server
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
    - name: create index.html
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }}) has been customized by Ansible\n"
        dest: "{{ web_root }}/index.html"
